### ISSUE TITLE
Windows versions

### ISSUE THREAD

**Issue by martinjras** [ua-parser/uap-csharp#15]
When i parse any Windows UA-string,  i only get the Family field set, never any of the others.
 
![image](https://cloud.githubusercontent.com/assets/3238947/13389113/b8b1bb4e-dec5-11e5-97a6-3f258a91a61c.png)

When i look at www.whatsmyua.com, which uses the JS version, the version field is set as well.

Why is this?

**Comment by enemaerke** [comment]
Hi @martinjras 

Without having tested it, it seems like an issue in the underlying regex'es rather than in the c# parser implementation. The NuGet package comes with a specific version of the regex'es available at the time of publishing the NuGet but there is a static overload on the Parser that allows you to push in a newer version. 

Try to fetch the newest regex'es from [uap-core](https://github.com/ua-parser/uap-core), they are in a big yaml file, create a parser from that and check if these new regex'es fix the issue. If not, you should open an issue on the uap-core project instead

Hope this helps

**Comment by martinjras** [comment]
Hi @enemaerke ,
Thanks for your response.
I tested it, and you are right. The yaml is basically missing the os_version extract. And also the testcases in `test_os.yaml` doesn't specify any versions AT ALL for windows.
Thinking about it, it doesn't make sense at all to try and extract a version-number from the Windows product name. My first thought was to parse it out manually, and thus being able to do  < > = operations on the number. But imagine to only allow **Windows 8.1** and above to use a website, would then result in **Windows 95, 98, 2000** to be :+1:  :disappointed:
