### ISSUE TITLE
CPU doubled after starting use of UAParser

### ISSUE THREAD

**Issue by chris-infospace** [ua-parser/uap-csharp#27]
We are using the UAParser in my office to parse the user agent, and log browser, device, and OS information. However, when we added this to our system, we saw our CPU double. My suspicion is that this is because the regexes are not precompiled at startup. Could someone more familiar with the repo confirm?

![pasted image at 2017_08_24 02_26 pm](https://user-images.githubusercontent.com/17412984/29726499-ca685f62-8984-11e7-8c18-7cfffe46d26a.png)

**Comment by enemaerke** [comment]
Hi @chris-infospace 

I maintain this repo, though it is unfortunately getting very little attention these days since I am not currently actively using it in my day job. I did a spike a few years ago to examine if changing to precompiled regex had an impact on performance but I only focussed on parsing/sec and not CPU and did not include it since I saw no significant boost. Feel free to grab the UAParser.cs file (which includes everything) and switch to precompiled expressions if needed, I unfortunately cannot commit any time to creating an opt-in/opt-out wrapping around this.

**Comment by enemaerke** [comment]
Hi @chris-infospace

I actually ported the project to .net standard 1.0 and 1.3 yesterday and uploaded it to NuGet. The 1.3 version contains a setting that allows for compiled regular expressions to be used in constructing the internal regular expressions. You can try and run with that and see what effect it has on your resources.

**Comment by thyn** [comment]
Hi, we are using small cache in our projects. We've created small library for internal use. We are using it on web sites. It resolves cpu issue. If somebody needs we can push it to nuget.

**Comment by enemaerke** [comment]
@thyn That sounds like a generally useful thing, so pushing it to NuGet makes sense. I'd be happy to link to it from this project page if you'd like

**Comment by enemaerke** [comment]
Havent heard back on any NuGet/project to link to, so closing this
