### ISSUE TITLE
ClientInfo UA vs UserAgent

### ISSUE THREAD

**Issue by tb-mtg** [ua-parser/uap-csharp#45]
The ClientInfo class looks to have properties that hold the same values:
* ClientInfo.UserAgent 
* ClientInfo.UA

Are they both required or can 1 of these be removed to avoid confusion?

**Comment by enemaerke** [comment]
Thanks for reporting this. I see the confusion. I have just published an updated 3.1.38 on NuGet that marks the UserAgent property as Obsolete and to be removed in a future version. (I picked the UA property to survive in order to comply with this specs here: https://github.com/ua-parser/uap-core/blob/master/docs/specification.md)
