### ISSUE TITLE
How to get the type of a device?

### ISSUE THREAD

**Issue by aloisdg** [ua-parser/uap-csharp#58]
Hello,

I would like to get the type of a device as seen in the [official documentation](https://github.com/faisalman/ua-parser-js/blob/master/readme.md):

```
Possible 'device.type':
console, mobile, tablet, smarttv, wearable, embedded
```

How to get the type of a device with uap-csharp?

Thanks

**Comment by enemaerke** [comment]
The official reference for this library is https://github.com/ua-parser/ since this library is only a C# port of the core repository and the regex lilbraries within. The official documentation you link to is not something that is related to this library (as far as I can tell).

Since the core library does not specify device type, then this C# port will not be implementing that. You can add an issue to the core library to request that dimension to be added to the data

**Comment by enemaerke** [comment]
I'll close this issue since there has been no immediate reply or question
