### ISSUE TITLE
Issue with Windows 8.1

### ISSUE THREAD

**Issue by StefanoBalzarottiDos** [ua-parser/uap-csharp#8]
With windows 8.1 ParseOS returns:
family: "Windows 8.1" instead of "Windows" 
major: null
minor: null
patch:null
ParseUserAgent returns "Other" instead of Windows

**Comment by enemaerke** [comment]
@StefanoBalzarottiDos this is very likely an issue with the reg-ex definitions you are using rather than the actual c# implementation. The c# implementation imports the regex as a submodule, which has not been updated for a while. The lib should allow you to pass in a newer yaml file, which you can pull from the https://github.com/ua-parser/uap-core project.

If this does not work, you should post the issue on the https://github.com/ua-parser/uap-core project.

Hope this helps

**Comment by enemaerke** [comment]
Closing this, should be a regex issue
